version: '3.8'
services:
  ai-recruiting-platform-api:
    build:
      context: ./AiRecruitingPlatform.Api
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  ai-recruiting-platform:
    build:
      context: ./AiRecruitingPlatform.Blazor
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - ai-recruiting-platform-api
